---

- hosts: localhost
  roles:
        - destroy-ec2
  when: DbType | regex_search('^ec2')
        
- hosts: localhost
  roles:
        - destroy-rds
  when: DbType | regex_search('^rds')
        
- hosts: localhost
  roles:
        - destroy-redshift
  when: DbType | regex_search('^redshift')


