# prototyping to set ideas

# In all cases, the dataset must be generated
- hosts: localhost
  roles:
        - dataset
        
- hosts: localhost
  roles:
        - build-ec2
  when: DbType | regex_search('^ec2')
        
- hosts: localhost
  roles:
        - build-rds
  when: DbType | regex_search('^rds')
        
- hosts: localhost
  roles:
        - build-redshift
  when: DbType | regex_search('^redshift')

# the above commands must have registered the variable "endpoint" which is basically
# how to connect to the database

- hosts: localhost
  roles:
        - bench

- hosts: localhost
  roles:
        - destroy-ec2
  when: DbType | regex_search('^ec2')
        
- hosts: localhost
  roles:
        - destroy-rds
  when: DbType | regex_search('^rds')
        
- hosts: localhost
  roles:
        - destroy-redshift
  when: DbType | regex_search('^redshift')


